#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

submenu "Utilities" {
	if [ ${grub_platform} == "efi" ]; then
		# Only use this utilities if GRUB is launched in UEFI mode
		menuentry "GDisk" {
			insmod fat
			insmod chain
			search --no-floppy --set=root --file /EFI/tools/gdisk_x64.efi
			chainloader /EFI/tools/gdisk_x64.efi
		}
	fi
}

menuentry "System shutdown" {
	echo "System shutting down..."
	halt
}

menuentry "System reboot" {
	echo "System rebooting..."
	reboot
}

